lib/viewer.coffee

Simple change to the Skim viewer command to handle files with spaces.

Escape pdf and textiles in case they have spaces

---

lib/builder.coffee

The comments on #3 made me realise that user_options still wasn't working as expected on latexmk. Basically with multiple options is was getting a command line like:
`latexmk -cd -e -f -pdf -interaction=nonstopmode -synctex=1 -latexoption="first_option",-latexoption="second_option" file.tex`
While the options showed up, they weren't being honoured. Digging into it, it appeared that options was being set to `["-cd", "-e", "-f", "-#{user_program}", "-interaction=nonstopmode", "-synctex=1", ["-latexmk=\"first_option\"", "-latexmk=\"second_option\""]]`, hence the bad behaviour. This PR fixes that.

Fix multiple options for latexmk

---

lib/builder.coffee

1. See #9. I also tend to use texlive on Windows.
1. I've changed things so the default is to assume latexmk except on Windows (previously the logic assumed we were on Windows if not on OS X or Linux).

Support texlive on Windows

---

keymaps/latextools.cson

Not much of a "feature", this just seems like it might be a saner way of handling keybindings, splitting them into three groups (more are possible *if* we need them):
1. All platforms
1. OS X
1. Not-OS X

Better keymap arrangement

---

lib/viewer.coffee

This doesn't appear to be necessary with Sumatra 3.1, but with Sumatra 2.5.2, not setting this flag caused it to open a new window per compilation.

Run Sumatra with -reuse-instance

---

lib/completion-manager.coffee

At least for me using `\addbibresource{}` wasn't properly finding bibliography files, since `\addbibresource{}` requires a `.bib` extension for BibLaTeX to properly find the bibliography.
The line in question compiles to something like this:
```javascript
var b, bibs;
bibs = ((function() {
var i, len, results;
if (path.extname(b) === '.bib') {
return path.join(filedir, b.trim());
} else {
results = [];
for (i = 0, len = bibs.length; i < len; i++) {
b = bibs[i];
results.push(path.join(filedir, b.trim() + '.bib'));
}
return results;
}
})());
```
In other words, **if** the file name has an extension '.bib', just return the path to the file as a string, otherwise, build the expected list. (Note, too, that `b` in that first conditional is actually going to be the current value of `raw_bibs`) …

Fix \addbibresource{}

---

lib/completion-manager.coffee
lib/latextools.coffee

Essentially, here's how I reproduced #21:
* Open a new window with a tex document and a non-editable buffer (**Settings** works nicely)
* Reload the window (**Window: Reload** from the palette)
The underlying issue is that while there is code that attempts to ensure it is only run on tex editors that have a recognised tex extension, when `refCiteComplete()` gets run it loads the active TextEditor which may or may not be the same text editor the event was triggered on.
For most TextEditors, this means we are running unnecessary code which may cause unexpected behaviour, but only with something like the **Settings** view which is a TextEditor but does not support the `getCursorPosition()` function do we get an actual error.
Long story short, this PR passes the observed TextEditor to …

Fix for issue #21

---

lib/latextools.coffee

Noticed these while looking in the console... Inconsequential, but removes a couple of warnings.

Reformat config object to address a couple of typos

---

lib/builder.coffee

Title says it all... 
`TextEditor#save()` only works if the buffer already has a file name associated with it. With this change, if you try to build an unsaved, unnamed buffer, it will display the save dialog. Cancelling the save dialog aborts the build (since no file name gets set).

Display a SaveAs dialog if build is run with an unsaved text editor

---

lib/viewer.coffee

changed condition under which errors from calling the viewer are shown such that a missing executable throws an error on the user console

fixed missing "view" errors under windows

---

lib/latextools.coffee

I accidentally broke the keybinding in #22. This fixes this by moving the command to the text editor and using that for completions.

Fix ref-cite-completion command

---

lib/ltconsole.coffee

This is intended to fix some less-than-optimal behaviour in the CSS hack for the console:
1. Exit out of the loop over stylesheets once we've found the correct sheet.
1. Default to inserting the rule at the end of the file.

Improvements for Console CSS code

---

lib/builder.coffee
lib/ltutils.coffee
lib/parsers/tex-directive-parser.coffee
spec/parsers/tex-directive-parser-spec.coffee

This modifies `parse_tex_directives` to provide an `onlyFor` parameter to limit the returned directives. The main intention is to make searching for a single directive more efficient, since, once found, we can stop reading lines.
As part of this, I've switched to using an implementation that relies on optional parameters passed as an object to the function. It makes things a bit clearer when using `onlyFor` and neither of the other two optional parameters.

Provide an onlyFor parameter to limit scope of directives returned

---

lib/viewer.coffee

This is one of the things pointed out in #28: when the PDF file doesn't exist, we still call the viewer resulting in a (possible bizarre) error message. This pre-empts this by only calling the viewer if the PDF file exists.

Write error to console when PDF does not exist

---

lib/views/ltconsole-view.coffee

Title says it all.
I couldn't figure this out initially, but came across [this](https://discuss.atom.io/t/cant-select-panel-text/15453).

Make the text in the console selectable

---

lib/builder.coffee
lib/completion-manager.coffee
lib/ltutils.coffee
lib/parsers/get-bib-completions.coffee
lib/snippet-manager.coffee
lib/viewer.coffee

Replaces Javascript alerts with Atom's built-in [notifications API](https://atom.io/docs/api/latest/NotificationManager).

atom.notifications for warnings and errors

---

snippets/latex.cson

- incorrect title for _Rightarrow_ definition
- _mathit_ and _mathbf_ defined twice
- prefix _bb_ used for _mathrm_ already used for _mathbb_ -> propose prefix _rm_ for _mathrm_

Corrected inconsistencies in snippet definitions

---

lib/snippet-manager.coffee

Fixes #82. Basically, snippet text with commands in it ended up looking like this:
```
\\\\$1cmd\\{\emph{something}\\}
^
```
The indicated slash would be eliminated somewhere in snippet processing. I've fixed this for all the functions by replacing `\` with `\\` before its added to a snippet.
Additionally, the calls to `setTextInBufferRange(range, "")` where creating their own undo checkpoint which was undesirable, so that undoing, e.g., wrapInCommand results first in blanking all the text and one would have to undo it again to restore the original text. Now only one undo is required, making the insertion of the snippet look like an atomic operation.

Properly escape `\` in snippet text and use transactions where needed

---

lib/commands/delete-temp-files.coffee

The delete-temp-files command currently doesn't work with double extensions, like `.synctex.gz`. This fixes that.

Ensure files with double extensions are deleted

---

lib/viewers/okular-viewer.coffee

Fixes a dumb copy-and-paste error. Name of viewer class for Okular changed from SumatraViewer -> OkularViewer. This is purely an aesthetic change.

Fix name of okular viewer

---

keymaps/latextools.cson
lib/completion-manager.coffee
lib/latextools.coffee

This is a proposal for how to get the cite / ref autocompletions a bit more responsive: it simply makes them respond to a particular key press, using the keymap.
The keymap could be a bit challenging since we'd then be responsible for actually inserting the appropriate text / snippet, but Atom provides a way around this by allowing us to call `abortKeyBinding()`, which simply tells Atom to continue processing the key binding as if we hadn't created a key map at all. We can then continue processing, i.e., checking if we should bring up the pop-up and displaying it.
I've moved the check for whether we should display the pop-up into a `setTimeout` call. I'm not sure whether or not this is necessary, but I figured it would be a good idea to allow Atom some time (50ms) to process the keypress. …

Launch completions from keypress

---

lib/latextools.coffee

I don't completely understand what happened in #65, but it looks like somehow the module global value was set (i.e. the required module was loaded) but the instance specific value never got set. I can't figure out how to reproduce the issue, but this (hopefully) corrects the behaviour, since it ensures that `requireIfNeeded` will check the instance value.

Fixes require if needed to (hopefully) address #65.

---

lib/viewers/base-viewer.coffee
lib/viewers/okular-viewer.coffee

See [SublimeText/LaTeXTools#730](https://github.com/SublimeText/LaTeXTools/issues/730#issuecomment-219309706). Essentially, this ensures that we always open the document in the Okular unique session, even if Okular has been previously opened.

Ensure okular always launched using --unique

---

menus/latextools.cson

Hide menu items in non-latex files, in order not to clutter up the editor.

Hide menu items in non-latex files.
